# Generated by Django 4.1.7 on 2023-04-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postinfo',
            name='html_code',
        ),
        migrations.AddField(
            model_name='postinfo',
            name='htmlCode',
            field=models.TextField(default='Nothing'),
        ),
    ]
