# Generated by Django 4.1.7 on 2023-04-20 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_postinfo_html_code_postinfo_htmlcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinfo',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postinfo',
            name='id',
            field=models.AutoField(default='0', primary_key=True, serialize=False),
        ),
    ]
