# Generated by Django 4.1.7 on 2023-04-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_postinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinfo',
            name='thumbnail',
            field=models.ImageField(default='island.png', upload_to='post_thumbnails'),
        ),
    ]
