# Generated by Django 4.1.7 on 2023-04-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_postinfo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinfo',
            name='thumbnail',
            field=models.ImageField(default='post_thumbnails/island.png', upload_to='post_thumbnails'),
        ),
    ]
