# Generated by Django 4.1.7 on 2023-04-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_postinfo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinfo',
            name='post_views',
            field=models.IntegerField(default=0),
        ),
    ]
